language: node_js
node_js:
  - 14
before_deploy:
  - npm install -g pkg
  - pkg . -t node14-linux-x64,node14-macos-x64,node14-win-x64
deploy:
  provider: releases
  api_key: $GIT_OAUTH
  file: 
  - "node-http-win.exe"
  - "node-http-linux"
  - "node-http-macos"
  skip_cleanup: true
  draft: true
script: node ci.js
