language: node_js
node_js:
  - 14
before_deploy:
  - npm install -g pkg
  - pkg .
deploy:
  provider: releases
  api_key: $GIT_OAUTH
  file: 
  - "node-http-win"
  - "node-http-linux"
  - "node-http-macos"
  skip_cleanup: true
  draft: true
script: chmod 777 node-http-linux && ./node-http-linux
